import type { LevelConfig } from "../models/LevelModel";

export const levels: LevelConfig[] = [
  {
    id: 1,
    title: "2와 3만 사용",
    targets: [12, 18, 24, 36],
    moves: 20,
    timeLimitSeconds: 100,
    availablePrimes: [2, 3],
    obstacles: [],
    starThresholds: [1600, 2600, 3800],
    hintPolicy: "auto",
    wrongDragPenalty: false,
    specialsEnabled: false,
    // 수집량은 목표들의 실제 소인수 합을 넘지 않게 맞춤
    objectives: { maxDragsPerTarget: 2, minLongChains: 1, longChainLength: 3, collectPrimes: { 2: 6, 3: 4 } },
  },
  {
    id: 2,
    title: "2, 3, 5 사용",
    targets: [20, 30, 45, 60],
    moves: 22,
    timeLimitSeconds: 110,
    availablePrimes: [2, 3, 5],
    obstacles: [],
    starThresholds: [1900, 3100, 4500],
    hintPolicy: "auto",
    wrongDragPenalty: false,
    specialsEnabled: false,
    objectives: { maxDragsPerTarget: 2, minLongChains: 1, longChainLength: 3, collectPrimes: { 5: 4 } },
  },
  {
    id: 3,
    title: "같은 소수 반복",
    targets: [32, 45, 72, 98],
    moves: 24,
    timeLimitSeconds: 120,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [],
    starThresholds: [2200, 3600, 5200],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 2, longChainLength: 3, collectPrimes: { 2: 8, 3: 4 } },
  },
  {
    id: 4,
    title: "긴 연결 유도",
    targets: [90, 120, 150, 180],
    moves: 24,
    timeLimitSeconds: 125,
    availablePrimes: [2, 3, 5],
    obstacles: [],
    starThresholds: [2600, 4300, 6200],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 4, longChainLength: 4, collectPrimes: { 3: 6, 5: 5 } },
  },
  {
    id: 5,
    title: "제한 이동",
    targets: [84, 90, 126, 140],
    moves: 18,
    timeLimitSeconds: 120,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [],
    starThresholds: [2500, 4100, 5900],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 7: 4 } },
  },
  {
    id: 6,
    title: "불필요한 소수 포함",
    targets: [63, 70, 84, 105],
    moves: 24,
    timeLimitSeconds: 130,
    availablePrimes: [2, 3, 5, 7, 11],
    obstacles: [],
    starThresholds: [2600, 4300, 6200],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 7: 5 } },
  },
  {
    id: 7,
    title: "소수 7 도입",
    targets: [42, 98, 126, 147],
    moves: 25,
    timeLimitSeconds: 130,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [],
    starThresholds: [2800, 4600, 6600],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 7: 8 } },
  },
  {
    id: 8,
    title: "합성수 장애물",
    targets: [84, 90, 120, 126],
    moves: 28,
    timeLimitSeconds: 145,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [{ type: "compositeIce", row: 2, col: 4, value: 12 }],
    starThresholds: [3200, 5200, 7400],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 2: 8, 3: 5 } },
  },
  {
    id: 9,
    title: "소수 13 도입",
    targets: [78, 130, 156, 195, 260],
    moves: 36,
    timeLimitSeconds: 160,
    availablePrimes: [2, 3, 5, 13],
    obstacles: [{ type: "compositeIce", row: 1, col: 3, value: 26 }],
    starThresholds: [4000, 6500, 9200],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 13: 5 } },
  },
  {
    id: 10,
    title: "13·17과 특수 사탕",
    targets: [221, 255, 286, 390, 455],
    moves: 42,
    timeLimitSeconds: 180,
    availablePrimes: [2, 3, 5, 7, 11, 13, 17],
    obstacles: [
      { type: "compositeIce", row: 1, col: 1, value: 30 },
      { type: "primeLock", row: 4, col: 6, value: 221 },
    ],
    starThresholds: [5200, 8400, 11800],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 4, longChainLength: 4, collectPrimes: { 13: 4, 17: 3 } },
  },
];
