import type { LevelConfig } from "../models/LevelModel";

export const levels: LevelConfig[] = [
  {
    id: 1,
    title: "2와 3만 사용",
    targets: [12, 18, 24, 36],
    moves: 20,
    timeLimitSeconds: 100,
    availablePrimes: [2, 3],
    obstacles: [],
    starThresholds: [2200, 3600, 5000],
    hintPolicy: "auto",
    wrongDragPenalty: false,
    specialsEnabled: false,
    objectives: { maxDragsPerTarget: 2, minLongChains: 1, longChainLength: 3, collectPrimes: { 2: 6, 3: 4 } },
  },
  {
    id: 2,
    title: "2, 3, 5 사용",
    targets: [20, 30, 45, 60],
    moves: 22,
    timeLimitSeconds: 110,
    availablePrimes: [2, 3, 5],
    obstacles: [],
    starThresholds: [2600, 4200, 5900],
    hintPolicy: "auto",
    wrongDragPenalty: false,
    specialsEnabled: false,
    objectives: { maxDragsPerTarget: 2, minLongChains: 1, longChainLength: 3, collectPrimes: { 5: 4 } },
  },
  {
    id: 3,
    title: "같은 소수 반복",
    targets: [32, 45, 72, 98],
    moves: 24,
    timeLimitSeconds: 120,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [],
    starThresholds: [3000, 4800, 6700],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 2, longChainLength: 3, collectPrimes: { 2: 8, 3: 4 } },
  },
  {
    id: 4,
    title: "긴 연결 유도",
    targets: [90, 120, 150, 180],
    moves: 24,
    timeLimitSeconds: 125,
    availablePrimes: [2, 3, 5],
    obstacles: [],
    starThresholds: [3600, 5800, 8000],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 4, longChainLength: 4, collectPrimes: { 3: 6, 5: 5 } },
  },
  {
    id: 5,
    title: "제한 이동",
    targets: [84, 90, 126, 140],
    moves: 18,
    timeLimitSeconds: 120,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [],
    starThresholds: [3400, 5400, 7600],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 7: 4 } },
  },
  {
    id: 6,
    title: "불필요한 소수 포함",
    targets: [63, 70, 84, 105],
    moves: 24,
    timeLimitSeconds: 130,
    availablePrimes: [2, 3, 5, 7, 11],
    obstacles: [],
    starThresholds: [3600, 5800, 8000],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 7: 5 } },
  },
  {
    id: 7,
    title: "소수 7 도입",
    targets: [42, 98, 126, 147],
    moves: 25,
    timeLimitSeconds: 130,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [],
    starThresholds: [3800, 6100, 8500],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 7: 8 } },
  },
  {
    id: 8,
    title: "합성수 장애물",
    targets: [84, 90, 120, 126],
    moves: 28,
    timeLimitSeconds: 145,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [{ type: "compositeIce", row: 2, col: 4, value: 12 }],
    starThresholds: [4300, 6800, 9500],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 3, longChainLength: 4, collectPrimes: { 2: 8, 3: 5 } },
  },
  {
    id: 9,
    title: "여러 목표 수",
    targets: [90, 126, 140, 150, 168, 180],
    moves: 38,
    timeLimitSeconds: 165,
    availablePrimes: [2, 3, 5, 7],
    obstacles: [],
    starThresholds: [5600, 8800, 12300],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 4, longChainLength: 4, collectPrimes: { 3: 8, 7: 4 } },
  },
  {
    id: 10,
    title: "특수 사탕 활용",
    targets: [220, 330, 396, 462, 660, 990],
    moves: 42,
    timeLimitSeconds: 180,
    availablePrimes: [2, 3, 5, 7, 11],
    obstacles: [
      { type: "compositeIce", row: 1, col: 1, value: 30 },
      { type: "primeLock", row: 4, col: 6, value: 110 },
    ],
    starThresholds: [7000, 11000, 15500],
    hintPolicy: "manual",
    wrongDragPenalty: true,
    specialsEnabled: true,
    objectives: { maxDragsPerTarget: 2, minLongChains: 5, longChainLength: 5, collectPrimes: { 11: 5, 7: 5 } },
  },
];
